name: Merge a develop

on:
  push:
    branches:
      - 'feature**'
  pull_request:
    branches:
      - 'feature**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover -s tests

  merge_to_develop:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:

      - name: Extract branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - uses: actions/checkout@master

      - name: Merge ${{ env.BRANCH_NAME }} -> develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: develop
          message: Merge ${{ env.BRANCH_NAME }} into develop
          github_token: ${{ secrets.MISO_SECRET }}
        # uses: tukasz/direct-merge-action@master
        # with:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   source-branch: ${{ env.BRANCH_NAME }}
        #   target-branch: develop
