name: CI

on:
  push:
    branches:
      - feature004
      - feature005
      - feature006
  pull_request:
    branches:
      - feature004
      - feature005
      - feature006

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover -s tests

  merge_to_develop:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Merge feature branch -> develop 
        run: |
          git fetch origin develop:develop
          git checkout develop
          git merge --no-ff ${GITHUB_REF##*/} -m "Merge ${GITHUB_REF##*/} into develop"
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.MISO_SECRET }}
  